version: '3.0'
services:
  mongo:
    container_name: mongo_db
    image: mongo:3.6.21
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/data/db
    networks:
      - default
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24